### ISSUE TITLE
Suspense not possible in Datatable

### ISSUE THREAD

**Issue by joywin2003** [joywin2003/Acadium#1]
In the `src/components/tables/faculty/faculty-table.tsx` folder,

```
<Suspense fallback={<div>Loading data...</div>}>
      <DataTable searchKey="name" columns={columns} data={data} />
</Suspense>
```

the above wont work cause of lazy laoding requiring default import but datatable is not a default import and if i show default then itll show the below error

```
Type 'ColumnDef<Faculty>[]' is not assignable to type 'ColumnDef<unknown, unknown>[]'.
Type 'ColumnDef<Faculty>' is not assignable to type 'ColumnDef<unknown, unknown>'
```

**Comment by Vyshnav001** [comment]
add this
<DataTable searchKey="name" columns={columns as ColumnDef<unknown, unknown>[]}  data={data ?? []} />

**Comment by joywin2003** [comment]
That looks like a next level jugad, Should I use it or better rely on something else(I already did) @Vyshnav001
